name: aliyundrive-checkin
on:
  schedule:
  - cron: 0 16 * * *
  workflow_dispatch:

permissions:
  contents: write  # 赋予读写权限
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Detection Code
        uses: actions/checkout@v4
      
      - name: Caching Python Dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            !~/.cache/pip/log/debug.log
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            
      - name: Install requirements
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          
      - name: Run checkin
        run: |
          python3 ./main.py --token_string "${{ secrets.TOKEN }}"
        env:
          PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }}
          SERVERCHAN_SENDKEY: ${{ secrets.SCKEY }}
          WECOM_TOKENS: ${{ secrets.WECOM_TOKENS }}
          WECOM_WEBHOOK: ${{ secrets.WECOM_WEBHOOK }}
          BARK_DEVICEKEY: ${{ secrets.BARK_DEVICEKEY }}
          FEISHU_DEVICEKEY: ${{ secrets.FEISHU_DEVICEKEY }}
      - uses: gautamkrishnar/keepalive-workflow@master
